# Generated by Django 3.2.8 on 2021-10-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=60)),
                ('server', models.CharField(max_length=60)),
                ('script', models.CharField(max_length=60)),
                ('exectime', models.TimeField()),
            ],
        ),
    ]
