# Generated by Django 3.2.8 on 2021-10-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='history',
            name='returncode',
            field=models.IntegerField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='terminal',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
