# Generated by Django 3.2.8 on 2021-10-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211014_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='exectime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='returncode',
            field=models.IntegerField(),
        ),
    ]
